kafka:
  brokers:
    - "localhost:9092"
  topic: "logs"
  group_id: "log-processor"
crypto:
  fields_to_encrypt:
    - "passport"
    - "snils"
vault:
  address: "http://localhost:8200"
  token: "my-root-token"
  transit_path: "transit"
  key_name: "kafka-encryption"
clickhouse:
  address: "localhost"
  port: 9000
  login: "default"
  password: "default"
worker_pool:
  worker_count: 4
  channel_buffer_size: 100
batch:
  size: 10
  flush_interval: "5s"
